### PR TITLE
Perfect number

### PR DESCRIPTION
**Pull request by ghost**
Program to check whether the number entered by the user is a perfect number.

starred proof
perfect number

### CODE REVIEW

**Comment by Kritikaadhikarii** [comment]
Great going !! Looks like you haven't starred this repo. Do make sure to do that. Also add a proof of the output of the code in description and a screenshot of starred repo.

**Comment by ghost** [comment]
This is my first HacktoberFest so it means a lot! Thank you :)
Done. 
@Kritikaadhikarii

**Comment by Kritikaadhikarii** [comment]
Great going. All the best, your pr has been merged now !!

**Comment by ghost** [comment]
Can you suggest any other ways I can contribute? Can I have your discord if you don't mind? I would love to take your guidance, improve myself and contribute more significantly.

**Pull request merged**
